# 46 제너레이터와 async

## 46.1 제너레이터란?

1. 제너레이터 함수는 함수 호출자에게 함수 실행의 제어권을 양도할 수 있다.  
   일반 함수를 호출하면 제어권이 함수에게 넘어가고 함수 코드를 일괄 실행한다. 즉, 함수 호출자는 함수를 호출한 이후 함수 실행을 제어할 수 없다.  
   반대로 제너레이터 함수는 함수 실행을 호출자가 제어할 수 있다. 다시 말해, 함수 호출자가 함수 실행을 일시 중지시키거나 재개시킬 수 있다. 이것을 함수 호출자에게 양도(yield)한다고 한다.
2. 제너레이터 함수는 함수 호출자와 함수의 상태를 주고받을 수 있다.  
   함수가 실행되고 잇는 동안에는 함수 외부에서 함수 내부로 값을 전달하여 함수의 상태를 변경할 수 없다.  
   저네러이터 함수는 함수 호출자에게 상태를 전달할 수 있고 함수 호출자로부터 상태를 전달받을 수도 있다.
3. 제너레이터 함수를 호출하면 제너레이터 객체를 반환한다.  
   제너레이터 함수를 호출하면 함수 코드를 실행하는 것이 아니라 이터러블이면서 동시에 이터레이터인 제너레이터 객체를 반환한다.

## 46.2 제너레이터 함수의 정의

제너레이터 함수는 `function*` 키워드로 선언한다. 그리고 하나 이상의 `yield` 표현식을 포함한다.

```js
function* genDecFunc() {
  yield 1;
}

const genExpFunc = function* () {
  yield 1;
};

const obj = {
  *genObjMethod() {
    yield 1;
  },
};

class MyClass {
  *genClassMethod() {
    yield 1;
  }
}
```

애스터리스크(\*)의 위치는 `function` 키워드와 함수 이름 사이라면 어디든지 상관없다. 하지만 일관성을 유지하기 위해 `function` 키워드 바로 뒤에 붙이는 것을 권장한다.

제너레이터 함수는 화살표 함수로 정의할 수 없다.  
그리고 `new` 연산자와 함께 생성자 함수로 호출할 수 없다.

## 46.3 제너레이터 객체

제너레이터 함수를 호출하면 일반 함수처럼 함수 코드 블록을 실행하는 것이 아니라 제너레이터 객체를 생성해 반환한다. 이 객체는 이터러블이면서 동시에 이터레이터이다.

다시 말해, 제너레이터 객체는 `Symbol.iterator` 메서드를 상속받는 이터러블이면서 `value`, `done` 프로퍼티를 갖는 이터레이터 리절트 객체를 반환하는 `next` 메서드를 소유하는 이터레이터다.

```js
function* genFunc() {
  yield 1;
  yield 2;
  yield 3;
}

const generator = genFunc();

console.log(Symbol.iterator in generator); // true
console.log('next' in generator); // true
```

- `next` 메서드를 호출하면 제너레이터 함수의 `yield` 표현식까지 코드 블록을 실행하고 `yield`된 값을 `value` 프로퍼티 값으로, `false`를 `done` 프로퍼티 값으로 갖는 이터레이터 리절트 객체를 반환한다.
- `return` 메서드를 호출하면 인수로 전달받은 값을 `value` 프로퍼티 값으로, `true`를 `done` 프로퍼티 값으로 갖는 이터레이터 리절트 객체를 반환한다.

```js
function* genFunc() {
  try {
    yield 1;
    yield 2;
    yield 3;
  } catch (e) {
    console.error(e);
  }
}

const generator = genFunc();

console.log(generator.next()); // {value: 1, done: false}
console.log(generator.return('End!')); // {value: 'End!', done: true}
console.log(generator.throw('Error!')); // {value: undefined, done: true}
```

- `throw` 메서드를 호출하면 인수로 전달받은 에러를 발생시키고 `undefined`를 `value` 프로퍼티 값으로, `true`를 `done` 프로퍼티 값으로 갖는 이터레이터 리절트 객체를 반환한다.

## 46.4 제너레이터의 일시 중지와 재개

제너레이터는 `yield` 키워드와 `next` 메서드를 통해 실행을 일시 중지했다가 필요한 시점에 다시 재개할 수 있다.

이 함수는 일반 함수처럼 한 번에 코드 블록의 모든 코드를 일괄 실행하는 것이 아니라 `yield` 표현식까지만 실행한다. `yield` 키워드는 제너레이터 함수의 실행을 일시 중지시키거나 `yield` 키워드 뒤에 오는 표현식의 평가 결과를 제너레이터 함수 호출자에게 반환한다.

```js
function* genFunc() {
  yield 1;
  yield 2;
  yield 3;
}

const generator = genFunc();
console.log(generator.next()); // {value: 1, done: false}
console.log(generator.next()); // {value: 2, done: false}
console.log(generator.next()); // {value: 3, done: false}
console.log(generator.next()); // {value: undefined, done: true}
```

제너레이터 객체의 `next` 메서드를 호출하면 `yield` 표현식까지 실행되고 일시 중지된다. 이때 함수의 제어권이 호출자로 양도된다.

이 후 `next` 메서드를 반복 호출하여 `yield` 표현식까지 실행과 일시 중지를 반복하다가 제너레이터 함수가 끝까지 실행되면 `next` 메서드가 반환하는 이터레이터 리절트 객체의 `value` 프로퍼티에는 제너레이터 함수의 반환값이 할당되고 `done` 프로퍼티에는 제너레이터 함수가 끝까지 실행되었음을 나타내는 `true`가 할당된다.

그리고 이터레이터의 `next` 메서드와 달리 제너레이터 객체의 `next`에는 인수를 전달할 수 있는데 전달한 인수는 제너레이터 함수의 `yield` 표현식을 할당받는 변수에 할당된다.

```js
function* genFunc() {
  // 여기서 yield된 값 1은 next 메서드가 반환한 이터레이터 리절트 객체의 value 프로퍼티에 할당된다.
  // x 변수에는 아무것도 할당되지 않았다. 이는 다음 next에 결정된다.
  const x = yield 1;

  // 두 번째 호출에 전달한 인수 10은 첫 번째 yield 표현식을 할당받는 변수 x 에 할당된다.
  // yield된 값 x + 10은 next 메서드가 반환한 이터레이터 리절트 객체의 value 프로퍼티에 할당된다.
  const y = yield x + 10;

  // 세 번째 next 메서드를 호출할 때 전달한 인수 20은 두 번째 yield 표현식을 할당받는 y 변수에 할당된다.
  // 즉, const y = yield (x + 10);은 세 번째 next 메서드를 호출했을 때 완료된다.
  // 제너레이터 함수의 반환값 x + y는 next 메서드가 반환한 이터레이터 리절트 객체의 value 프로퍼티에 할당된다. (일반적으로 제너레이터의 반환값은 의미가 없음)
  // return은 종료의 의미가 크다.
  return x + y;
}

const generator = genFunc();

// 처음 호출하는 next 메서드에는 인수를 전달해도 무시된다.
// 이터레이터 리절트 객체의 value 프로퍼티에는 첫 번째 yield된 값 1이 할당된다.
let res = generator.next();
console.log(res); // {value: 1, done: false}

// next 메서드에 인수로 전달한 10은 genFunc 함수의 x 변수에 할당된다.
// value 프로퍼티에는 두 번째 yield된 값 20이 할당된다.
res = generator.next(10);
console.log(res); // {value: 20, done: false}

// next 메서드에 인수로 전달한 20은 genFunc 함수의 y 변수에 할당된다.
// value 프로퍼티에는 두 번째 yield된 값 30이 할당된다.
res = generator.next(20);
console.log(res); // {value: 30, done: true}
```

이처럼 제너레이터 함수를 사용하면 함수 호출자는 `next` 메서드를 통해 `yield` 표현식까지 함수를 실행시켜 제너레이터 객체가 관리하는 상태를 꺼내올 수 있고, `next` 메서드에 인수를 전달해서 제너레이터 객체의 상태를 밀어넣을 수 있다.

## 46.5 제너레이터의 활용

### 46.5.1 이터러블의 구현

제너레이터 함수를 사용하면 이터레이터 프로토콜을 준수해 이터러블을 생성하는 방식보다 간단히 이터러블을 구현할 수 있다.

```js
// 무한 이터러블을 생성하는 함수(이터레이션 프로토콜)
const infiniteFibonacci = (function () {
  let [pre, cur] = [0, 1];

  return {
    [Symbol.iterator]() {
      return this;
    },
    next() {
      [pre, cur] = [cur, pre + cur];
      return { value: cur };
    },
  };
})();

for (const num of infiniteFibonacci) {
  if (num > 10000) break;
  console.log(num); // 1 2 3 5 8 ... 2584 4181 6765
}
```

```js
// 무한 이터러블을 생성하는 함수(제너레이터 함수)
const infiniteFibonacci = (function* () {
  let [pre, cur] = [0, 1];

  while (true) {
    [pre, cur] = [cur, pre + cur];
    yield cur;
  }
})();

for (const num of infiniteFibonacci) {
  if (num > 10000) break;
  console.log(num); // 1 2 3 5 8 ... 2584 4181 6765
}
```

### 46.5.2 비동기 처리

제너레이터 함수는 함수 호출자와 함수의 상태를 주고받을 수 있다.  
이러한 특성을 활용하면 프로미스를 사용한 비동기 처리를 동기 처리처럼 구현할 수 있다.(후속 처리 메서드 없이)

```js
const fetch = require('node-fetch');

const async = (generatorFunc) => {
  const generator = generatorFunc();

  const onResolved = (arg) => {
    const result = generator.next(arg);

    return result.done ? result.value : result.value.then((res) => onResolved(res));
  };

  return onResolved;
};

async(function* fetchTodo() {
  const url = 'https://jsonplaceholder.typicode.com/todos/1';

  const response = yield fetch(url);
  const todo = yield response.json();
  console.log(todo);
  // {userId: 1, id: 1, title: 'delectus aut autem', completed: false}
})();
```

1. `async` 함수가 호출되면 인수로 전달받은 제너레이터 함수 `fetchTodo`를 호출하여 제너레이터 객체를 생성하고 `onResolved` 함수를 반환한다. 이 함수는 상위 스코프의 `generator` 변수를 기억하는 클로저다. 이것을 즉시 호출하여 생성한 제너레이터 객체의 `next` 메서드를 처음 호출한다.
2. `next` 메서드가 처음 호출되면 제너레이터 함수 `fetchTodo`의 첫 번째 `yield` 문까지 실행된다. `fetch` 함수가 반환한 프로미스가 `resolve`한 `Response` 객체를 `onResolved` 함수에 인수로 전달하면서 재귀 호출한다.
3. `onResolved` 함수에 인수로 전달된 `Response` 객체를 `next` 메서드에 인수로 전달하면서 `next` 메서드를 두 번째로 호출한다. 이때 인수로 전달한 `Response` 객체는 `fetchTodo`의 `response` 변수에 할당되고 두 번째 `yield` 문까지 실행된다.
4. 두 번째 `yield`된 `response.json` 메서드가 반환한 프로미스가 `resolve`한 todo객체를 `onResolved` 함수에 인수로 전달하면서 재귀 호출한다.
5. `onResolved` 함수에 인수로 전달된 todo 객체를 `next` 메서드에 인수로 전달하면서 세 번째로 호출한다. 인수로 전달한 todo 객체를 `fetchTodo` 함수의 `todo` 변수에 할당하고 `fetchTodo`가 끝까지 실행된다.
6. 여기서 반환한 이터레이터 리절트 객체의 `done` 프로퍼티 값이 `true`, 즉 끝까지 실행되었다면 `value` 프로퍼티 값으로 `undefined`를 반환하고 처리를 종료한다.

## 46.6 async/await

`async`/`await`은 프로미스를 기반으로 동작한다. 이것을 사용하면 프로미스의 후속 처리 메서드에 콜백 함수를 전달해서 비동기 처리 결과를 후속 처리할 필요 없이 마치 동기 처리처럼 프로미스를 사용할 수 있다.

```js
async function fetchTodo() {
  const url = 'https://jsonplaceholder.typicode.com/todos/1';

  const response = await fetch(url);
  const todo = await response.json();
  console.log(todo);
  // {userId: 1, id: 1, title: 'delectus aut autem', completed: false}
}

fetchTodo();
```

### 46.6.1 async 함수

`await` 키워드는 반드시 `async` 함수 내부에서 사용해야 한다. 그리고 언제나 프로미스를 반환한다.  
만약 함수에서 명시적으로 프로미스를 반환하지 않더라도 `async` 함수는 암묵적으로 반환값을 `resolve`하는 프로미스를 반환한다.

### 46.6.2 await 키워드

`await` 키워드는 프로미스가 settled 상태가 될 때까지 대기하다가 해당 상태가 되면 프로미스가 `resolve`한 처리 결과를 반환한다. 이 키워드는 반드시 프로미스 앞에서 사용해야 한다.

이처럼 `await` 키워드는 다음 실행을 일시 중지시켰다가 프로미스가 settled 상태가 되면 다시 재개한다.

```js
async function foo() {
  const a = await new Promise((resolve) => setTimeout(() => resolve(1), 3000));
  const b = await new Promise((resolve) => setTimeout(() => resolve(2), 2000));
  const c = await new Promise((resolve) => setTimeout(() => resolve(3), 1000));

  console.log([a, b, c]); // [1, 2, 3]
}

foo(); // 약 6초 소요된다.
```

다만 앞선 결과가 다음 비동기 처리에 영향을 주지 않는 위 예제같은 경우에는 `Promise.all` 메서드를 사용하는 것이 좋다.

### 46.6.3 에러 처리

비동기 함수의 콜백 함수를 호출했을 때 함수를 호출한 것은 비동기 함수가 아니므로 try...catch 문을 사용해 에러를 캐치할 수 없다.

`async`/`await`에서 에러 처리는 try...catch 문을 사용할 수 있다.

```js
const foo = async () => {
  try {
    const wrongUrl = 'https://wrong.url';

    const response = await fetch(wrongUrl);
    const data = await response.json();
    console.log(data);
  } catch (err) {
    console.error(err); // TypeError: Failed to fetch
  }
};

foo();
```

위 예제의 `catch`문은 HTTP 통신에서 발생한 네트워크 에러뿐 아니라 `try` 코드 블록 내의 모든 문에서 발생한 일반적인 에러까지 모두 캐치할 수 있다.

`async` 함수 내에서 `catch` 문을 사용해서 에러 처리를 하지 않으면 `async` 함수는 발생한 에러를 `reject`하는 프로미스를 반환한다.  
따라서 `catch`를 사용하지 않고 `Promise.prototype.catch` 후속 처리 메서드를 사용해 에러를 캐치할 수도 있다.
