# 45. Promise

## 45.1 비동기 처리를 위한 콜백 패턴의 단점

### What is Callback - 제대로 이해해보자 콜백!

- 콜백함수를 설명할 때에는 변수의 유효범위(scope)에 대한 이야기, **동기/비동기(synchronous/Asynchronous)**처리에 대한 이야기도 하면 좋을 것 같다

**1. 동기** : 하나의 요청이 오면 완료가 된 후 다음 요청을 실행하는 방식 - 순차적 로직흐름

**2. 비동기** : 어떤 요청이 오면 완료가 되기 전에 다음 요청을 실행하는 방식동시 효율적 처리 가능, 즉시 응답이 오는 것이 아니기 때문에 예상 밖의 결과 나올수도 있음

> ✔콜백함수란
> 
> 1. **다른 함수의 인자**로써 이용되는 함수.
> 2. **어떤 이벤트에 의해 호출**되어지는 함수.
- 콜백함수는 때로는 **가독성이나 코드 재사용** 면에서도 사용 된다.
- **비동기 방식으로 작성된 함수를 동기 처리**하기 위해 필요하다.

---

> **콜백이 필요한 경우**는 어떤 때인가?
> 
- 콜백이 없는 세상아..  (setTimeout는 비동기 함수다.)

```jsx
function findUser(id) {
  let user;
  setTimeout(function () {
    console.log("waited 0.1 sec.");
    user = {
      id: id,
      name: "User" + id,
      email: id + "@test.com",
    };
  }, 100); // -> user 객체가 무시되어버림..
  return user;
}

const user = findUser(1);
console.log("user:", user);
```

- 위 코드 실행 결과
    
    user: undefined
    waited 0.1 sec.
    
- 위 예시에서 발생하는 문제를 해결하고자, 아래 코드처럼 콜백을 이용해보자.

```jsx
function findUserAndCallBack(id, cb) {
  setTimeout(function () {
    console.log("waited 0.1 sec.");
    const user = {
      id: id,
      name: "User" + id,
      email: id + "@test.com",
    };
    cb(user);
  }, 100);
}

findUserAndCallBack(1, function (user) {
  console.log("user:", user);
});
```

- 위 코드 실행 결과
    
    waited 0.1 sec.
    user: {id: 1, name: "User1", email: "1@test.com"}
    
    → 결과값을 바로 리턴받지 않고, 그 결과값을 통해 처리할 로직을 콜백 함수로 넘겨서 제대로 구현을 하였다.
    

### 45.1.1 Callback Hell (콜백 지옥)

> **콜백 헬: 비동기 처리에 함수의 매개변수로 넘겨지는 콜백 함수가 반복되어 코드의 들여쓰기가 깊어지는 현상**
> 
- 콜백 지옥에 갇히면 가독성이 떨어지고 코드 수정하기가 어려워진다.
- 콜백 함수가 3번 반복되면서 코드의 들여쓰기가 계속해서 깊어지는 것을 확인할 수 있다.

```jsx
const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      console.log(JSON.parse(xhr.response));
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

get("https://jsonplaceholder.typicode.com/posts/1");
```

> **비동기함수**: 함수 내부에 비동기로 동작하는 코드를 포함한 함수
> 

```jsx
const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      return JSON.parse(xhr.response);
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

const response = get("https://jsonplaceholder.typicode.com/posts/1");
console.log(response);
```

- **처리 결과**를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다.
- 예를 들어 아래 코드처럼, **let 같은 상위 스코프**의 변수에 할당하면… (변수에 값이 원하는 바가 제대로 할당되지 않을 것임.)

```jsx
let todos;

const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      todos = JSON.parse(xhr.response);
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

get("https://jsonplaceholder.typicode.com/posts/1");
console.log(todos);
```

- 또 아래의 한 예시 코드를 보자. 코드를 통해 유추해보건대, 첫 번째 포스트를 가져왔으면, 유저 아이디를 가지고 유저 정보를 가져오려는 상황이다.
- 이 작업을 순차적으로 하려고 한다면, 아래 코드처럼 콜백 함수 호출이 중첩되어 복잡도가 높아지는 현상이 발생, **콜백 헬(**callback hell)에 갇히게 된다.

```jsx
const get = (url, callback) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      callback(JSON.parse(xhr.response));
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

const url = "https://jsonplaceholder.typicode.com";
get(url + "/posts/1", ({ userId }) => {
  console.log(userId);

  get(url + "/users/" + userId, (userInfo) => {
    console.log(userInfo);
  });
});
```

- 콜백 지옥의 또 다른 예시 🔽 (비동기를 동기처럼 처리하고 싶었는데..ㅜㅜ)

```jsx
get("/step1", (a) => {
  get(`/step2/${a}`, (b) => {
    get(`/step3/${c}`, (c) => {
      get(`/step3/${c}`, (c) => {
        console.log(d);
      });
    });
  });
});
```

### 45.1.2 에러 처리의 한계

- 콜백 패턴의 심각한 문제점, **에러 처리가 곤란하다는 것**

```jsx
try {
  setTimeout(() => {
    throw new Error("Error!");
  }, 1000);
} catch (e) {
  console.error("캐치한 에러", e); // -> 이게 나오길 기대했는데..!!!
}
```

- **에러는 호출자 방향으로 전파된다.**
- setTimeout 함수의 콜백함수를 호출한 것은 **setTimeout 함수가 아니다.**
- catch 블록에서 캐치되지 않는다.

### setTimeout을 좀 알아볼까?

[setTimeout() - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout)

## 45.2 Promise의 생성

### 먼저 Promise란

**`Promise`**객체는 비동기 작업이 맞이할 미래의 완료 또는 실패와 그 결과 값을 나타낸다.

- Promise를 생성해보자.

```jsx
// 프로미스 생성
const promise = new Promise((resolve, reject) => {
    // Promise 함수의 콜백 함수 내부에서 비동기 처리를 수행한다.
    if (/* 비동기 처리 성공 */) {
        resolve('result');
    } else { /* 비동기 처리 실패 */
        reject('failure reason');
    }
})
```

```jsx
const promiseGet = (url) => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open("GET", url);
    xhr.send();

    xhr.onload = () => {
      if (xhr.status === 200) {
        resolve(JSON.parse(xhr.response));
      } else {
        reject(new Error(xhr.status));
      }
    };
  });
};

// promiseGet 함수는 프로미스를 반환한다.
promiseGet("https://jsonplaceholder.typicode.com/posts/1");
```

| 프로미스의 상태 정보 | 의미 | 상태 변경 조건 |
| --- | --- | --- |
| pending | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |
| fulfilled | 비동기 처리가 수행된 상태(성공) | resolve 함수 호출 |
| rejected | 비동기 처리가 수행된 상태(실패) | reject 함수 호출 |
- `Promise`의 상태는 `resolve` 또는 `reject`함수를 호출 하는 것으로 결정된다.
- 비동기 처리 성공: resolve 함수를 호출해 프로미스를 fulfilled 상태로 변경
- 비동기 처리 실패: reject 함수를 호출해 프로미스를 rejected 상태로 변경
- fullfilled 또는 rejected 상태를 **settled** 상태라고 한다.
    - settled 상태가 되면 다른 상태로 변화할 수 없다.
- 비동기 처리 상태와 더불어 비동기 처리 결과도 상태로 갖는다.

```jsx
const fulfilled = new Promise((resolve) => resolve(1));
```

```jsx
const rejected = new Promise((_, reject) =>
  reject(new Error("error occurred"))
);
```

다시 한줄 요약 → `Promise`**는 비동기 처리 상태와 처리 결과를 관리하는 객체!**

## **45.3 Promise 의 후속 처리 메서드**

- `Promise`의 비동기 처리 상태가 변화하면, **후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출된다.**
- 모든 후속 처리 메서드는 Promise를 반환하며, 비동기로 동작한다.

### **45.3.1 Promise.prototype.then**

- 두 개의 콜백 함수를 인수로 전달 받는다
    - Promise가 `fulfilled` 상태가 되면 호출, 성공 처리 callback
    - Promise가 `rejected` 상태가 되면 호출, 실패 처리 callback
    
    ```jsx
    // fulfilled
    new Promise((resolve) => resolve("fulfilled")).then(
      (v) => console.log(v),
      (e) => console.error(e)
    );
    
    // rejected
    new Promise((_, reject) => reject(new Error("rejected"))).then(
      (v) => console.log(v),
      (e) => console.error(e)
    );
    ```
    

### **45.3.2 Promise.prototype.catch**

- 한 개의 콜백 함수를 인수로 전달 받는다
    - 프로미스가 rejected 상태인 경우 호출
- then(undefined, onRejected)와 동일

```jsx
// rejected
new Promise((_, reject) => reject(new Error("rejected"))).catch((e) =>
  console.error(e)
);
```

### **45.3.3 Promise.prototype.finally**

- 한 개의 콜백 함수를 인수로 전달 받는다
    - 프로미스의 성공 또는 실패와 상관없이 **무조건 한 번 호출**
- 상태와 상관없이 공통적으로 수행해야 할 처리 내용이 있을 때 유용

```jsx
new Promise(() => {}).finally(() => console.log("finally"));
```

## 45.4 Promise의 에러 처리

```jsx
const wrongUrl = "https://jsonplaceholder.typicode.com/XXX/1";

// 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl).then(
  (res) => console.log(res),
  (err) => console.error(err)
);
```

- catch를 사용해 처리할 수도 있다. (권장 X)

```jsx
const wrongUrl = "https://jsonplaceholder.typicode.com/XXX/1";

// 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
promiseGet(wrongUrl)
  .then((res) => console.log(res))
  .catch((err) => console.error(err));
```

- catch 메서드를 호출하면 내부적으로 then(undefined, onRejected)을 호출한다.
    - 단, then 메서드의 두 번째 콜백 함수는 첫 번째 콜백 함수에서 발생한 에러를 캐치하지 못하고, 코드가 복잡해져서 **가독성이 좋지 않다**
    
    ```jsx
    promiseGet("https://jsonplaceholder.typicode.com/todos/1").then(
      (res) => console.xxx(res),
      (err) => console.error(err)
    );
    ```
    
    - 위 코드처럼, catch 메서드를 모든 then 메서드를 호출한 이후에 호출하면 then 메서드 내부에서 발생한 에러까지 모두 캐치할 수 있다.

## **45.5 Promise Chanining**

```jsx
const url = "https://jsonplaceholder.typicode.com";

// id가 1인 post의 userId를 획득
promiseGet(`${url}/posts/1`)
  // 취득한 post의 userId로 user 정보를 획득
  .then(({ userId }) => promiseGet(`${url}/users/${userId}`))
  .then((userInfo) => console.log(userInfo))
  .catch((err) => console.error(err));
```

- then, catch, finally 후속 처리 메서드는 항상 Promise를 반환하므로 연속적으로 호출할 수 있다.

| 후속 처리 메서드 | 콜백 함수의 인수 | 후속 처리 메서드의 반환값 |
| --- | --- | --- |
| then | promiseGet 함수가 반환한 프로미스가 resolve한 값(id가 1인 post) | 콜백 함수가 반환한 프로미스 |
| then | 첫 번째 then메서드가 반환한 프로미스가 resolve한 값(post의 userId로 취득한 user 정보) | 콜백 함수가 반환한 값(undefined)을 resolve한 프로미스 |
| catch*에러가 발생하지 않으면 호출되지 않는다. | promiseGet 함수 또는 앞선 후속 처리 메서드가 반환한 프로미스가 reject한 값 | 콜백 함수가 반환한 값(undefined)을 resolve한 프로미스 |

이는 async/await를 통해 해결할 수 있다. 

```jsx
const url = "https://jsonplaceholder.typicode.com";

(async () => {
  // id가 1인 post의 userId를 획득
  const { userId } = await promiseGet(`${url}/posts/1`);

  // 취득한 post의 userId로 user 정보를 획득
  const userInfo = await promiseGet(`${url}/users/${userId}`);

  console.log(userInfo);
})();
```

## 45.6 Promise의 Static Method

### **45.6.1 Promise.resolve / Promise.reject**

- **이미 존재하는 값**을 래핑하여 `Promise`를 생성하기 위해 사용됨

```jsx
// 배열을 resolve하는 프로미스를 생성
const resolvePromise = Promise.resolve([1, 2, 3]);
resolvePromise.then(console.log);`

const resolvePromise = new Promise((resolve) => resolve([1, 2, 3]));
resolvePromise.then(console.log);
```

```jsx
// 에러 객체를 reject하는 프로미스를 생성
const rejectedPromise = Promise.reject(new Error("Error"));
rejectedPromise.catch(console.log);
const rejectedPromise = new Promise((_, reject) => reject(new Error("Error")));
rejectedPromise.catch(console.log);
```

### **45.6.2 Promise.all**

- 여러 개의 비동기 처리를 **모두 병렬 처리**할 때 사용

```jsx
const requestData1 = () =>
  new Promise((resolve) => setTimeout(() => resolve(1), 3000));
const requestData2 = () =>
  new Promise((resolve) => setTimeout(() => resolve(2), 2000));
const requestData3 = () =>
  new Promise((resolve) => setTimeout(() => resolve(3), 1000));

// 세 개의 비동기 처리를 순차적으로 처리
const res = [];
requestData1()
  .then((data) => {
    res.push(data);
    return requestData2();
  })
  .then((data) => {
    res.push(data);
    return requestData3();
  })
  .then((data) => {
    res.push(data);
    console.log(res);
  }).catch(console.error);
```

- 세 개의 비동기 처리를 순차적으로 처리
- 총 6초 이상 소요됨
- 각 비동기 처리는 서로 의존하지 않고 **개별적으로 수행**
- 순차적으로 처리할 필요가 없음
- 바로 위 코드는 아래처럼 깔끔하게 정리 가능.

```jsx
Promise.all([requestData1(), requestData2(), requestData3()])
  .then(console.log)
  .catch(console.error);
```

### **45.6.3 Promise.race**

- 가장 먼저 `fulfilled` 상태가 된 `Promise`의 처리 결과를 `resolve`하는 새로운 Promise 반환
- `Promise`가 `rejected` 상태가 되면 `Promise.all` 메서드와 동일하게 처리

```jsx
Promise.race([
  new Promise((resolve) => setTimeout(() => resolve(1), 3000)),
  new Promise((resolve) => setTimeout(() => resolve(2), 2000)),
  new Promise((resolve) => setTimeout(() => resolve(3), 1000)),
])
  .then(console.log)
  .catch(console.error);
```

### **45.6.4 allSettled**

- `Promise`를 요소로 갖는 배열 등의 iterable을 인수로 전달
- 전달받은 `Promise`가 모두 settled 상태(비동기 처리가 수행된 상태)가 되면 처리 결과를 배열로 반환함

```jsx
Promise.allSettled([
  new Promise((resolve) => setTimeout(() => resolve(1), 2000)),
  new Promise((_, reject) =>
    setTimeout(() => reject(new Error("Error!")), 1000)
  ),
]).then(console.log);
```

## **45.7 Microtask Queue**

```jsx
setTimeout(() => console.log(1), 0);

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3));
```

- `Promise`의 후속 처리 메서드의 콜백 함수는 태스크 큐가 아니라 마이크태스크 큐에 저장함.
- **마이크로태스크 큐는 태스크 큐보다 우선순위가 높다**
- 이벤트 루프는 콜 스택이 비면 먼저 마이크로태스크 큐에서 대기하고 있는 함수를 가져와 실행한다.
- 이후 **마이크로태스크 큐가 비면** 태스크 큐에서 대기하고 있는 함수를 가져와 실행한다.

## **45.8 fetch**

> **fetch** : XMLHttpRequest 객체와 마찬가지로 HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API
> 
- XMLHttpRequest 객체보다 사용법이 간단한고 Promise를 지원함

```jsx
const promise = fetch(url, [, option[)
```

- fetch 함수는 **HTTP 응답을 나타내는 Response 객체를 래핑한 Promise 객체**를 반환함

```jsx
fetch("https://jsonplaceholder.typicode.com/todos/1").then((response) =>
  console.log(response)
);

fetch("https://jsonplaceholder.typicode.com/todos/1")
  // response는 HTTP응답을 나타내는 Response 객체다.
  // json 메서드를 사용하여 Response 객체에서 HTTP 응답 몸체를 취득하여 역직렬화한다.
  .then((response) => response.json())
  // json은 역직렬화된 HTTP 응답 몸체다.
  .then((json) => console.log(json));
```

---

### 느낀 점

- 그동안 백엔드에서 온 응답이 Promise 형태여서 ‘오, 비동기 처리에 의한 응답은 항상 Promise 형태이군’ 이라는 위험한 생각을 했다.
- Promise가 무엇인가? 라는 질문 뒤에는, ‘왜 Promise가 필요한가?’ 가 뒤따른다.
    - 항상 어떤 기술은 해당 기술을 선행하는 기술이 어떠한 문제가 있기 때문인데.. 왜 그동안은 이런 부분을 생각하지 못한 것일까..?
    - 진정한 기술 부채를 체감하고 있다.😮🥺😂
- 현재 레벨 1 마지막 미션에서 구현하는 기능 일부가 비동기 처리인데, Promise의 필요성과 개념을 이해하고 나니 한결 마음이 편안해졌다.
    - 무언가에 빚진다는 느낌이 해소되었달까..
    - 또 어디에 빚졌는지, 앞으로 알아볼 생각에 벌써부터 흥미진진하다😂😃😄