# 47장 에러 처리

## **에러가 발생하지 않는 코드를 작성하는 것은 불가능하다.**

#### 대신 try…catch 문을 사용해 발생한 에러에 적절하게 대응하면 프로그램이 강제 종료되지 않고 계속해서 코드를 실행할 수 있다.

```jsx
// 에러 처리
try {
  // 실행할 코드(에러가 발생할 가능성이 있는 코드)
} catch (err) {
  // try 코드 블록에서 에러가 발생하면 이 코드 블록의 코드가 실행된다.
  // err에는 try 코드 블록에서 발생한 Error 객체가 전달된다.
} finally {
  // 에러 발생과 상관없이 반드시 한 번 실행된다.
}
```

#### 또한 if문, 단축 평가 또는 옵셔널 체이닝 연산자를 사용해 에러 처리를 할 수 있다.

```jsx
const $button = document.querySelector("button"); // null
$button?.classList.add("disabled"); //옵셔널 체이닝 연산자로 에러 처리
```

## **Error 생성자 함수는 에러 객체를 생성한다.**

### Error 생성자 함수에는 에러를 상세히 설명하는 에러 메세지를 인수로 전달할 수 있다.

- message 프로퍼티 : Error 생성자 함수에 인수로 전달한 에러 메세지
- stack 프로퍼티 : 에러를 발생시킨 콜스택의 호출 정보를 나타내는 문자열이며 디버깅 목적으로 사용한다.
- 자바스크립트는 Error 생성자 함수를 포함해 7가지 에러 객체를 생성할 수 있는 Error 생성자 함수를 제공한다.

  | 생성자 함수    | 인스턴스                                                                       |
  | -------------- | ------------------------------------------------------------------------------ |
  | Error          | 일반적 에러 객체                                                               |
  | SyntaxError    | 자바스크립트 문법에 맞지 않는 문을 해설할 때 발생하는 에러 객체                |
  | ReferenceError | 참조할 수 없는 식별자를 참조했을 때 발생하는 에러 객체                         |
  | TypeError      | 피연산자 또는 인수의 데이터 타입이 유효하지 않을 때 발생하는 에러 객체         |
  | RangeError     | 숫자값의 허용 범위를 벗어났을 때 발생하는 에러 객체                            |
  | URIError       | encodeURI 또는 decodeURI 함수에 부적절한 인수를 전달했을 때 발생하는 에러 객체 |
  | EvalError      | eval 함수에서 발생하는 에러 객체                                               |

### Error 생성자 함수로 에러 객체를 생성한다고 에러가 발생하는 것은 아니다. 즉, 에러 객체 생성과 에러 발생은 의미가 다르다.

- **에러를 발생시키려면 try 코드 블록에서 throw 문으로 에러 객체를 던져야 한다.**

  ```jsx
  try {
    throw new Error("something wrong");
  } catch (error) {
    console.log(error);
  }
  ```

- throw 문의 표현식은 어떤 값이라도 상관없지만 일반적으로 에러 객체를 지정한다. 에러를 던지면 catch 문의 에러 변수가 생성되고 던져진 에러 객체가 할당된다. 그리고 catch 코드 블록이 실행되기 시작한다.

## **에러는 호출자 방향으로 전파된다.**

### 즉, 콜 스택의 아래 방향(실행 중인 실행 컨텍스트가 푸시되기 직전에 푸시된 실행 컨텍스트 방향)으로 전파된다.

- throw된 에러를 캐치하지 않으면 호출자 방향으로 전파되고, 어디에서도 캐치하지 않으면 프로그램은 강제 종료된다.
- **주의할 것은 비동기 함수인 setTimeout이나 프로미스 후속 처리 메서드의 콜백 함수는 호출자가 없다는 것이다.** setTimeout이나 프로미스 후속 처리 메서드의 콜백 함수는 태스크 큐나 마이크로태스크 큐에 일시 저장되었다가 콜 스택이 비면 이벤트 루프에 의해 콜 스택으로 푸시되어 실행된다. 이때 콜 스택에 푸시된 콜백 함수의 실행 컨텍스트는 콜 스택의 가장 하부에 존재하게 되고, 에러를 전파할 호출자가 존재하지 않는다.
